import type { Locale } from "@/i18n/routing";

export type FieldType = "text" | "textarea" | "number";

export type ContentField = {
  key: string;
  page: string;
  type: FieldType;
  label: string;
  shared?: boolean;
};

export const pages: { id: string; label: string }[] = [
  { id: "nav", label: "Menu a patička" },
  { id: "home", label: "Úvod" },
  { id: "apartment", label: "Apartmán" },
  { id: "santaPola", label: "Santa Pola" },
  { id: "pricing", label: "Ceník — texty" },
  { id: "rates", label: "Ceník — sazby (EUR)" },
  { id: "booking", label: "Rezervace" },
  { id: "contact", label: "Kontakt" },
  { id: "legal", label: "VOP" },
  { id: "welcome", label: "Welcome / hosté" },
];

export const fields: ContentField[] = [
  { key: "meta.siteName", page: "nav", type: "text", label: "Název webu" },
  { key: "nav.home", page: "nav", type: "text", label: "Menu: Úvod" },
  { key: "nav.apartment", page: "nav", type: "text", label: "Menu: Apartmán" },
  { key: "nav.santaPola", page: "nav", type: "text", label: "Menu: Santa Pola" },
  { key: "nav.pricing", page: "nav", type: "text", label: "Menu: Ceník" },
  { key: "nav.booking", page: "nav", type: "text", label: "Menu: Rezervace" },
  { key: "nav.contact", page: "nav", type: "text", label: "Menu: Kontakt" },
  { key: "nav.bookCta", page: "nav", type: "text", label: "Tlačítko rezervace" },
  { key: "footer.tagline", page: "nav", type: "text", label: "Patička — slogan" },
  { key: "footer.legal", page: "nav", type: "text", label: "Odkaz VOP" },
  { key: "footer.rights", page: "nav", type: "text", label: "Copyright" },
  { key: "host.name", page: "nav", type: "text", label: "Majitel — jméno" },
  { key: "host.note", page: "nav", type: "textarea", label: "Majitel — text pod CTA" },
  { key: "host.cta", page: "nav", type: "text", label: "Majitel — odkaz" },
  { key: "video.title", page: "apartment", type: "text", label: "Video — nadpis" },
  { key: "video.lead", page: "apartment", type: "textarea", label: "Video — perex" },

  { key: "home.heroEyebrow", page: "home", type: "text", label: "Hero — nadtitulek" },
  { key: "home.heroTitle", page: "home", type: "text", label: "Hero — nadpis" },
  { key: "home.heroLead", page: "home", type: "textarea", label: "Hero — perex" },
  { key: "home.ctaApartment", page: "home", type: "text", label: "CTA Apartmán" },
  { key: "home.ctaBook", page: "home", type: "text", label: "CTA Rezervace" },
  { key: "home.fact1Value", page: "home", type: "text", label: "Fakt 1 — hodnota" },
  { key: "home.fact1Label", page: "home", type: "text", label: "Fakt 1 — popis" },
  { key: "home.fact2Value", page: "home", type: "text", label: "Fakt 2 — hodnota" },
  { key: "home.fact2Label", page: "home", type: "text", label: "Fakt 2 — popis" },
  { key: "home.fact3Value", page: "home", type: "text", label: "Fakt 3 — hodnota" },
  { key: "home.fact3Label", page: "home", type: "text", label: "Fakt 3 — popis" },
  { key: "home.moodTitle", page: "home", type: "text", label: "Nálada — nadpis" },
  { key: "home.moodText", page: "home", type: "textarea", label: "Nálada — text" },
  { key: "home.placeTitle", page: "home", type: "text", label: "Santa Pola teaser — nadpis" },
  { key: "home.placeText", page: "home", type: "textarea", label: "Santa Pola teaser — text" },
  { key: "home.placeCta", page: "home", type: "text", label: "Santa Pola teaser — odkaz" },
  { key: "home.reviewsTitle", page: "home", type: "text", label: "Recenze — nadpis" },
  { key: "home.review1Name", page: "home", type: "text", label: "Recenze 1 — jméno" },
  { key: "home.review1Text", page: "home", type: "textarea", label: "Recenze 1 — text" },
  { key: "home.review2Name", page: "home", type: "text", label: "Recenze 2 — jméno" },
  { key: "home.review2Text", page: "home", type: "textarea", label: "Recenze 2 — text" },
  { key: "home.review3Name", page: "home", type: "text", label: "Recenze 3 — jméno" },
  { key: "home.review3Text", page: "home", type: "textarea", label: "Recenze 3 — text" },
  { key: "home.ctaBandTitle", page: "home", type: "text", label: "Spodní pruh — nadpis" },
  { key: "home.ctaBandText", page: "home", type: "textarea", label: "Spodní pruh — text" },

  { key: "apartment.metaTitle", page: "apartment", type: "text", label: "SEO titulek" },
  { key: "apartment.title", page: "apartment", type: "text", label: "Nadpis" },
  { key: "apartment.lead", page: "apartment", type: "textarea", label: "Perex" },
  { key: "apartment.p2", page: "apartment", type: "textarea", label: "Odstavec 2" },
  { key: "apartment.p3", page: "apartment", type: "textarea", label: "Odstavec 3" },
  { key: "apartment.p4", page: "apartment", type: "textarea", label: "Odstavec 4" },
  { key: "apartment.amenitiesTitle", page: "apartment", type: "text", label: "Vybavení — nadpis" },
  { key: "apartment.amenityAc", page: "apartment", type: "text", label: "Vybavení: klima" },
  { key: "apartment.amenityTv", page: "apartment", type: "text", label: "Vybavení: TV" },
  { key: "apartment.amenityWifi", page: "apartment", type: "text", label: "Vybavení: Wi-Fi" },
  { key: "apartment.amenityCoffee", page: "apartment", type: "text", label: "Vybavení: káva" },
  { key: "apartment.amenityTowels", page: "apartment", type: "text", label: "Vybavení: osušky" },
  { key: "apartment.amenityTransfer", page: "apartment", type: "text", label: "Vybavení: transfer" },
  { key: "apartment.amenityHost", page: "apartment", type: "text", label: "Vybavení: správce" },
  { key: "apartment.galleryTitle", page: "apartment", type: "text", label: "Galerie — nadpis" },
  { key: "apartment.gallery.living", page: "apartment", type: "text", label: "Alt: obývák" },
  { key: "apartment.gallery.kitchen", page: "apartment", type: "text", label: "Alt: kuchyně" },
  { key: "apartment.gallery.terrace", page: "apartment", type: "text", label: "Alt: terasa moře" },
  { key: "apartment.gallery.terraceSofa", page: "apartment", type: "text", label: "Alt: terasa posezení" },
  { key: "apartment.gallery.bedroom1", page: "apartment", type: "text", label: "Alt: ložnice 1" },
  { key: "apartment.gallery.bedroom2", page: "apartment", type: "text", label: "Alt: ložnice 2" },
  { key: "apartment.gallery.bath1", page: "apartment", type: "text", label: "Alt: koupelna 1" },
  { key: "apartment.gallery.bath2", page: "apartment", type: "text", label: "Alt: koupelna 2" },
  { key: "apartment.addressTitle", page: "apartment", type: "text", label: "Adresa — nadpis" },
  { key: "apartment.noLift", page: "apartment", type: "text", label: "Poznámka bez výtahu" },

  { key: "santaPola.metaTitle", page: "santaPola", type: "text", label: "SEO titulek" },
  { key: "santaPola.title", page: "santaPola", type: "text", label: "Nadpis" },
  { key: "santaPola.lead", page: "santaPola", type: "textarea", label: "Perex" },
  { key: "santaPola.cityTitle", page: "santaPola", type: "text", label: "Město — nadpis" },
  { key: "santaPola.cityText", page: "santaPola", type: "textarea", label: "Město — text" },
  { key: "santaPola.beachesTitle", page: "santaPola", type: "text", label: "Pláže — nadpis" },
  { key: "santaPola.beachesText", page: "santaPola", type: "textarea", label: "Pláže — text" },
  { key: "santaPola.foodTitle", page: "santaPola", type: "text", label: "Jídlo — nadpis" },
  { key: "santaPola.foodText", page: "santaPola", type: "textarea", label: "Jídlo — text" },
  { key: "santaPola.tripsTitle", page: "santaPola", type: "text", label: "Výlety — nadpis" },
  { key: "santaPola.tripsText", page: "santaPola", type: "textarea", label: "Výlety — text" },
  { key: "santaPola.tabarcaTitle", page: "santaPola", type: "text", label: "Tabarca — nadpis" },
  { key: "santaPola.tabarcaText", page: "santaPola", type: "textarea", label: "Tabarca — text" },

  { key: "pricing.metaTitle", page: "pricing", type: "text", label: "SEO titulek" },
  { key: "pricing.title", page: "pricing", type: "text", label: "Nadpis" },
  { key: "pricing.lead", page: "pricing", type: "textarea", label: "Perex" },
  { key: "pricing.perNight", page: "pricing", type: "text", label: "Jednotka / noc" },
  { key: "pricing.minNights", page: "pricing", type: "text", label: "Min. noci — šablona ({n})" },
  { key: "pricing.includedTitle", page: "pricing", type: "text", label: "Cena zahrnuje — nadpis" },
  { key: "pricing.included", page: "pricing", type: "textarea", label: "Cena zahrnuje (odřádkování = položky)" },
  { key: "pricing.extrasTitle", page: "pricing", type: "text", label: "Příplatky — nadpis" },
  { key: "pricing.cleaningLabel", page: "pricing", type: "text", label: "Úklid — popisek" },
  { key: "pricing.transferLabel", page: "pricing", type: "text", label: "Transfer — popisek" },
  { key: "pricing.longStayLabel", page: "pricing", type: "text", label: "Dlouhodobá sleva — popisek" },
  { key: "pricing.termsTitle", page: "pricing", type: "text", label: "Platby a storno — nadpis" },
  { key: "pricing.terms", page: "pricing", type: "textarea", label: "Platby a storno" },
  { key: "pricing.licence", page: "pricing", type: "text", label: "Licence" },
  { key: "pricing.season.winter", page: "pricing", type: "text", label: "Sezóna zima" },
  { key: "pricing.season.spring", page: "pricing", type: "text", label: "Sezóna jaro" },
  { key: "pricing.season.summer", page: "pricing", type: "text", label: "Sezóna léto" },
  { key: "pricing.season.autumn", page: "pricing", type: "text", label: "Sezóna podzim" },
  { key: "pricing.month.1", page: "pricing", type: "text", label: "Měsíc 1" },
  { key: "pricing.month.2", page: "pricing", type: "text", label: "Měsíc 2" },
  { key: "pricing.month.3", page: "pricing", type: "text", label: "Měsíc 3" },
  { key: "pricing.month.4", page: "pricing", type: "text", label: "Měsíc 4" },
  { key: "pricing.month.5", page: "pricing", type: "text", label: "Měsíc 5" },
  { key: "pricing.month.6", page: "pricing", type: "text", label: "Měsíc 6" },
  { key: "pricing.month.7", page: "pricing", type: "text", label: "Měsíc 7" },
  { key: "pricing.month.8", page: "pricing", type: "text", label: "Měsíc 8" },
  { key: "pricing.month.9", page: "pricing", type: "text", label: "Měsíc 9" },
  { key: "pricing.month.10", page: "pricing", type: "text", label: "Měsíc 10" },
  { key: "pricing.month.11", page: "pricing", type: "text", label: "Měsíc 11" },
  { key: "pricing.month.12", page: "pricing", type: "text", label: "Měsíc 12" },

  { key: "rates.1", page: "rates", type: "number", label: "Leden EUR/noc", shared: true },
  { key: "rates.2", page: "rates", type: "number", label: "Únor EUR/noc", shared: true },
  { key: "rates.3", page: "rates", type: "number", label: "Březen EUR/noc", shared: true },
  { key: "rates.4", page: "rates", type: "number", label: "Duben EUR/noc", shared: true },
  { key: "rates.5", page: "rates", type: "number", label: "Květen EUR/noc", shared: true },
  { key: "rates.6", page: "rates", type: "number", label: "Červen EUR/noc", shared: true },
  { key: "rates.7", page: "rates", type: "number", label: "Červenec EUR/noc", shared: true },
  { key: "rates.8", page: "rates", type: "number", label: "Srpen EUR/noc", shared: true },
  { key: "rates.9", page: "rates", type: "number", label: "Září EUR/noc", shared: true },
  { key: "rates.10", page: "rates", type: "number", label: "Říjen EUR/noc", shared: true },
  { key: "rates.11", page: "rates", type: "number", label: "Listopad EUR/noc", shared: true },
  { key: "rates.12", page: "rates", type: "number", label: "Prosinec EUR/noc", shared: true },
  { key: "rates.min.1", page: "rates", type: "number", label: "Leden min. noci", shared: true },
  { key: "rates.min.2", page: "rates", type: "number", label: "Únor min. noci", shared: true },
  { key: "rates.min.3", page: "rates", type: "number", label: "Březen min. noci", shared: true },
  { key: "rates.min.4", page: "rates", type: "number", label: "Duben min. noci", shared: true },
  { key: "rates.min.5", page: "rates", type: "number", label: "Květen min. noci", shared: true },
  { key: "rates.min.6", page: "rates", type: "number", label: "Červen min. noci", shared: true },
  { key: "rates.min.7", page: "rates", type: "number", label: "Červenec min. noci", shared: true },
  { key: "rates.min.8", page: "rates", type: "number", label: "Srpen min. noci", shared: true },
  { key: "rates.min.9", page: "rates", type: "number", label: "Září min. noci", shared: true },
  { key: "rates.min.10", page: "rates", type: "number", label: "Říjen min. noci", shared: true },
  { key: "rates.min.11", page: "rates", type: "number", label: "Listopad min. noci", shared: true },
  { key: "rates.min.12", page: "rates", type: "number", label: "Prosinec min. noci", shared: true },
  { key: "rates.cleaning", page: "rates", type: "number", label: "Úklid EUR", shared: true },
  { key: "rates.transfer", page: "rates", type: "number", label: "Transfer EUR", shared: true },
  { key: "rates.longStayDiscount", page: "rates", type: "number", label: "Sleva % od 30 dní", shared: true },

  { key: "booking.metaTitle", page: "booking", type: "text", label: "SEO titulek" },
  { key: "booking.title", page: "booking", type: "text", label: "Nadpis" },
  { key: "booking.lead", page: "booking", type: "textarea", label: "Perex" },
  { key: "booking.from", page: "booking", type: "text", label: "Od" },
  { key: "booking.to", page: "booking", type: "text", label: "Do" },
  { key: "booking.guests", page: "booking", type: "text", label: "Počet osob" },
  { key: "booking.name", page: "booking", type: "text", label: "Jméno" },
  { key: "booking.email", page: "booking", type: "text", label: "E-mail" },
  { key: "booking.message", page: "booking", type: "text", label: "Zpráva" },
  { key: "booking.transfer", page: "booking", type: "text", label: "Transfer checkbox" },
  { key: "booking.submit", page: "booking", type: "text", label: "Odeslat" },
  { key: "booking.success", page: "booking", type: "textarea", label: "Děkujeme" },
  { key: "booking.error", page: "booking", type: "text", label: "Chyba odeslání" },
  { key: "booking.occupied", page: "booking", type: "text", label: "Termín obsazen" },
  { key: "booking.minNightsError", page: "booking", type: "text", label: "Málo nocí ({n})" },
  { key: "booking.nights", page: "booking", type: "text", label: "Noci" },
  { key: "booking.stay", page: "booking", type: "text", label: "Ubytování" },
  { key: "booking.total", page: "booking", type: "text", label: "Celkem" },
  { key: "booking.deposit", page: "booking", type: "text", label: "Záloha 50 %" },
  { key: "booking.legendFree", page: "booking", type: "text", label: "Legenda volno" },
  { key: "booking.legendBusy", page: "booking", type: "text", label: "Legenda obsazeno" },
  { key: "booking.faqTitle", page: "booking", type: "text", label: "FAQ nadpis" },
  ...Array.from({ length: 18 }, (_, i) => {
    const n = i + 1;
    return [
      { key: `faq.q${n}`, page: "booking" as const, type: "text" as const, label: `FAQ ${n} — otázka` },
      { key: `faq.a${n}`, page: "booking" as const, type: "textarea" as const, label: `FAQ ${n} — odpověď` },
    ];
  }).flat(),

  { key: "contact.metaTitle", page: "contact", type: "text", label: "SEO titulek" },
  { key: "contact.title", page: "contact", type: "text", label: "Nadpis" },
  { key: "contact.lead", page: "contact", type: "textarea", label: "Příběh" },
  { key: "contact.formTitle", page: "contact", type: "text", label: "Formulář — nadpis" },
  { key: "contact.submit", page: "contact", type: "text", label: "Odeslat zprávu" },
  { key: "contact.success", page: "contact", type: "text", label: "Zpráva odeslána" },
  { key: "contact.addressTitle", page: "contact", type: "text", label: "Adresa — nadpis" },

  { key: "legal.metaTitle", page: "legal", type: "text", label: "SEO titulek" },
  { key: "legal.title", page: "legal", type: "text", label: "Nadpis VOP" },
  { key: "legal.body", page: "legal", type: "textarea", label: "Text VOP" },

  { key: "welcome.metaTitle", page: "welcome", type: "text", label: "SEO titulek" },
  { key: "welcome.title", page: "welcome", type: "text", label: "Nadpis" },
  { key: "welcome.lead", page: "welcome", type: "textarea", label: "Perex" },
  { key: "welcome.checkin", page: "welcome", type: "text", label: "Check-in manuály" },
  { key: "welcome.guide", page: "welcome", type: "text", label: "Průvodce okolím" },
];

export const SHARED_LOCALE = "_";

export function isLocale(value: string): value is Locale {
  return ["cs", "en", "es", "de", "fr"].includes(value);
}
