import type { Locale } from "@/i18n/routing";
import { SHARED_LOCALE } from "./fields";

type Pack = Partial<Record<Locale | typeof SHARED_LOCALE, string>>;

export const seedTexts: Record<string, Pack> = {
  "meta.siteName": {
    cs: "Prázdniny ve Španělsku",
    en: "Holidays in Spain",
    es: "Vacaciones en España",
    de: "Ferien in Spanien",
    fr: "Vacances en Espagne",
  },
  "nav.home": { cs: "Úvod", en: "Home", es: "Inicio", de: "Start", fr: "Accueil" },
  "nav.apartment": {
    cs: "Apartmán",
    en: "Apartment",
    es: "Apartamento",
    de: "Apartment",
    fr: "Appartement",
  },
  "nav.santaPola": {
    cs: "Santa Pola",
    en: "Santa Pola",
    es: "Santa Pola",
    de: "Santa Pola",
    fr: "Santa Pola",
  },
  "nav.pricing": { cs: "Ceník", en: "Rates", es: "Tarifas", de: "Preise", fr: "Tarifs" },
  "nav.booking": {
    cs: "Rezervace",
    en: "Booking",
    es: "Reserva",
    de: "Buchung",
    fr: "Réservation",
  },
  "nav.contact": { cs: "Kontakt", en: "Contact", es: "Contacto", de: "Kontakt", fr: "Contact" },
  "nav.bookCta": {
    cs: "Zeptat se na termín",
    en: "Enquire about dates",
    es: "Consultar fechas",
    de: "Termin anfragen",
    fr: "Demander des dates",
  },
  "footer.tagline": {
    cs: "Klid u moře v Santa Pole",
    en: "Calm by the sea in Santa Pola",
    es: "Calma junto al mar en Santa Pola",
    de: "Ruhe am Meer in Santa Pola",
    fr: "Le calme au bord de la mer à Santa Pola",
  },
  "footer.legal": {
    cs: "Obchodní podmínky",
    en: "Terms",
    es: "Condiciones",
    de: "AGB",
    fr: "Conditions",
  },
  "footer.rights": {
    cs: "Residence Santa Pola",
    en: "Residence Santa Pola",
    es: "Residence Santa Pola",
    de: "Residence Santa Pola",
    fr: "Residence Santa Pola",
  },

  "home.heroEyebrow": {
    cs: "Santa Pola · Costa Blanca",
    en: "Santa Pola · Costa Blanca",
    es: "Santa Pola · Costa Blanca",
    de: "Santa Pola · Costa Blanca",
    fr: "Santa Pola · Costa Blanca",
  },
  "home.heroTitle": {
    cs: "Klid, moře a světlo Španělska",
    en: "Calm, sea and Spanish light",
    es: "Calma, mar y luz de España",
    de: "Ruhe, Meer und spanisches Licht",
    fr: "Calme, mer et lumière d’Espagne",
  },
  "home.heroLead": {
    cs: "Apartmán až pro 8 osob v Santa Pole, 15 minut od letiště Alicante a pár kroků od pláže. Místo, kde se dny zpomalí.",
    en: "An apartment for up to 8 guests in Santa Pola, 15 minutes from Alicante airport and a few steps from the beach. A place where the days slow down.",
    es: "Apartamento para hasta 8 personas en Santa Pola, a 15 minutos del aeropuerto de Alicante y a unos pasos de la playa. Un lugar donde los días se detienen.",
    de: "Apartment für bis zu 8 Personen in Santa Pola, 15 Minuten vom Flughafen Alicante und wenige Schritte vom Strand. Ein Ort, an dem die Tage langsamer werden.",
    fr: "Un appartement jusqu’à 8 personnes à Santa Pola, à 15 minutes de l’aéroport d’Alicante et à deux pas de la plage. Un lieu où les jours ralentissent.",
  },
  "home.ctaApartment": {
    cs: "Prohlédnout apartmán",
    en: "See the apartment",
    es: "Ver el apartamento",
    de: "Apartment ansehen",
    fr: "Voir l’appartement",
  },
  "home.ctaBook": {
    cs: "Zeptat se na termín",
    en: "Enquire about dates",
    es: "Consultar fechas",
    de: "Termin anfragen",
    fr: "Demander des dates",
  },
  "home.fact1Value": { cs: "110 m²", en: "110 m²", es: "110 m²", de: "110 m²", fr: "110 m²" },
  "home.fact1Label": {
    cs: "pro 6–8 osob",
    en: "for 6–8 guests",
    es: "para 6–8 personas",
    de: "für 6–8 Personen",
    fr: "pour 6–8 personnes",
  },
  "home.fact2Value": { cs: "200 m", en: "200 m", es: "200 m", de: "200 m", fr: "200 m" },
  "home.fact2Label": {
    cs: "od pláže Levante",
    en: "from Levante beach",
    es: "de la playa Levante",
    de: "vom Strand Levante",
    fr: "de la plage Levante",
  },
  "home.fact3Value": { cs: "15 min", en: "15 min", es: "15 min", de: "15 min", fr: "15 min" },
  "home.fact3Label": {
    cs: "od letiště Alicante",
    en: "from Alicante airport",
    es: "del aeropuerto de Alicante",
    de: "vom Flughafen Alicante",
    fr: "de l’aéroport d’Alicante",
  },
  "home.moodTitle": {
    cs: "Dny bez spěchu",
    en: "Unhurried days",
    es: "Días sin prisa",
    de: "Tage ohne Eile",
    fr: "Des jours sans hâte",
  },
  "home.moodText": {
    cs: "Objevte ideální místo pro dovolenou v Santa Pola. Apartmán nabízí výhled na moře a je pár kroků od pláže, restaurací a obchodů. Pro rodiny, skupiny i všechny, kdo hledají pohodlí a klid.",
    en: "Discover the best place to spend a holiday in Santa Pola. The apartment has a sea view and sits just steps from the beach, restaurants and shops. Perfect for families, groups and anyone looking for comfort and calm.",
    es: "Descubra el lugar ideal para unas vacaciones en Santa Pola. El apartamento tiene vistas al mar y está a unos pasos de la playa, restaurantes y tiendas. Perfecto para familias, grupos y quienes buscan comodidad y calma.",
    de: "Entdecken Sie den idealen Ort für Urlaub in Santa Pola. Das Apartment hat Meerblick und liegt nur wenige Schritte vom Strand, von Restaurants und Geschäften. Ideal für Familien, Gruppen und alle, die Komfort und Ruhe suchen.",
    fr: "Découvrez l’endroit idéal pour des vacances à Santa Pola. L’appartement offre une vue mer et se trouve à deux pas de la plage, des restaurants et des commerces. Parfait pour les familles, les groupes et tous ceux qui cherchent le confort et le calme.",
  },
  "home.placeTitle": {
    cs: "Santa Pola, město u moře",
    en: "Santa Pola, a town by the sea",
    es: "Santa Pola, un pueblo junto al mar",
    de: "Santa Pola, Stadt am Meer",
    fr: "Santa Pola, une ville au bord de la mer",
  },
  "home.placeText": {
    cs: "Krásné pláže, promenáda, přístav a místní trhy. Víc než 300 slunečných dní v roce a výlety na ostrov Tabarca, do Alicante nebo do Elche.",
    en: "Beautiful beaches, a promenade, a harbour and local markets. More than 300 sunny days a year, plus trips to Tabarca Island, Alicante or Elche.",
    es: "Playas hermosas, paseo marítimo, puerto y mercados locales. Más de 300 días de sol al año y excursiones a la isla de Tabarca, Alicante o Elche.",
    de: "Schöne Strände, Promenade, Hafen und lokale Märkte. Mehr als 300 Sonnentage im Jahr und Ausflüge nach Tabarca, Alicante oder Elche.",
    fr: "De belles plages, une promenade, un port et des marchés locaux. Plus de 300 jours de soleil par an, et des excursions à Tabarca, Alicante ou Elche.",
  },
  "home.placeCta": {
    cs: "Poznat Santa Polu",
    en: "Discover Santa Pola",
    es: "Descubrir Santa Pola",
    de: "Santa Pola entdecken",
    fr: "Découvrir Santa Pola",
  },
  "home.reviewsTitle": {
    cs: "Hlasy hostů",
    en: "Guest voices",
    es: "Voces de huéspedes",
    de: "Stimmen der Gäste",
    fr: "Voix des hôtes",
  },
  "home.review1Name": { cs: "Natalia", en: "Natalia", es: "Natalia", de: "Natalia", fr: "Natalia" },
  "home.review1Text": {
    cs: "Poloha apartmánu je skvělá, pláž je jen minutu od něj. Byt je velký a plně vybavený. Byli jsme překvapeni uvítacím dárkem. Skvělé místo s přáteli nebo rodinou.",
    en: "The location is excellent, the beach is a minute away. The apartment is large and fully equipped. We were surprised by the welcome gift. A wonderful place with friends or family.",
    es: "La ubicación es excelente, la playa está a un minuto. El piso es grande y totalmente equipado. Nos sorprendió el detalle de bienvenida. Un lugar maravilloso con amigos o familia.",
    de: "Die Lage ist großartig, der Strand ist nur eine Minute entfernt. Die Wohnung ist groß und voll ausgestattet. Das Willkommensgeschenk hat uns überrascht. Ein wunderbarer Ort mit Freunden oder Familie.",
    fr: "L’emplacement est excellent, la plage est à une minute. L’appartement est grand et entièrement équipé. Le cadeau de bienvenue nous a surpris. Un endroit formidable entre amis ou en famille.",
  },
  "home.review2Name": { cs: "David", en: "David", es: "David", de: "David", fr: "David" },
  "home.review2Text": {
    cs: "Nádherný byt, kompletně zrekonstruovaný, nechybí žádný detail. Bylo nás 8 a místa bylo dost. Má pěkný balkon s výhledem na moře. Určitě se vrátíme.",
    en: "A wonderful apartment, completely renovated, no detail missing. There were 8 of us and there was enough space. A lovely balcony with a sea view. We will definitely come back.",
    es: "Un apartamento maravilloso, completamente reformado, no falta ningún detalle. Éramos 8 y había espacio de sobra. Un balcón bonito con vistas al mar. Volveremos seguro.",
    de: "Ein wunderbares Apartment, komplett renoviert, kein Detail fehlt. Wir waren zu acht und es gab genug Platz. Ein schöner Balkon mit Meerblick. Wir kommen bestimmt wieder.",
    fr: "Un appartement magnifique, entièrement rénové, aucun détail ne manque. Nous étions 8 et il y avait assez de place. Un joli balcon avec vue mer. Nous reviendrons sans hésiter.",
  },
  "home.review3Name": { cs: "Barry", en: "Barry", es: "Barry", de: "Barry", fr: "Barry" },
  "home.review3Text": {
    cs: "Pěkný byt, správce nám obětavě umožnil check-in po půlnoci. Čekal uvítací balíček. Pokoje svěží a čisté, skvělé zatemnění, pohodlné matrace.",
    en: "A nice apartment, the manager kindly allowed a check-in after midnight. A welcome pack was waiting. Rooms were fresh and clean, excellent blackout blinds, comfortable mattresses.",
    es: "Piso agradable, el encargado nos permitió el check-in después de medianoche. Había un pack de bienvenida. Habitaciones frescas y limpias, estores oscuros y colchones cómodos.",
    de: "Schönes Apartment, der Verwalter ermöglichte uns den Check-in nach Mitternacht. Ein Willkommenspaket wartete. Zimmer frisch und sauber, gute Verdunkelung, bequeme Matratzen.",
    fr: "Bel appartement, le gestionnaire a accepté un check-in après minuit. Un panier de bienvenue nous attendait. Chambres fraîches et propres, occultation parfaite, matelas confortables.",
  },
  "home.ctaBandTitle": {
    cs: "Až budete chtít k moři",
    en: "When you are ready for the sea",
    es: "Cuando quiera ir al mar",
    de: "Wenn Sie ans Meer möchten",
    fr: "Quand vous aurez envie de mer",
  },
  "home.ctaBandText": {
    cs: "Napište nám termín. Ozveme se, ověříme volné dny a pošleme odkaz na zálohu.",
    en: "Tell us your dates. We will reply, check availability and send a deposit link.",
    es: "Escríbanos las fechas. Contestaremos, comprobaremos la disponibilidad y enviaremos el enlace de la señal.",
    de: "Schreiben Sie uns Ihren Zeitraum. Wir antworten, prüfen die Verfügbarkeit und senden den Link für die Anzahlung.",
    fr: "Indiquez-nous vos dates. Nous répondrons, vérifierons la disponibilité et enverrons le lien d’acompte.",
  },

  "apartment.metaTitle": {
    cs: "Apartmán · Prázdniny ve Španělsku",
    en: "Apartment · Holidays in Spain",
    es: "Apartamento · Vacaciones en España",
    de: "Apartment · Ferien in Spanien",
    fr: "Appartement · Vacances en Espagne",
  },
  "apartment.title": {
    cs: "Apartmán s výhledem na moře",
    en: "Apartment with a sea view",
    es: "Apartamento con vistas al mar",
    de: "Apartment mit Meerblick",
    fr: "Appartement avec vue mer",
  },
  "apartment.lead": {
    cs: "Prostorný apartmán o rozloze 110 m² byl kompletně zrekonstruován v roce 2024 a je ideální pro 6–8 osob. Leží jen 200 metrů od pláže Levante a 7 minut chůze od centra Santa Pola. Třetí patro bez výtahu — odměnou za pár schodů je výhled na moře a ostrov Tabarca.",
    en: "A spacious 110 m² apartment, fully renovated in 2024, ideal for 6–8 guests. It is 200 metres from Levante beach and a 7-minute walk from the centre of Santa Pola. Third floor without a lift — a few extra stairs are rewarded with a view of the sea and Tabarca Island.",
    es: "Apartamento de 110 m², reformado por completo en 2024, ideal para 6–8 personas. Está a 200 metros de la playa Levante y a 7 minutos a pie del centro de Santa Pola. Tercer piso sin ascensor: unos peldaños de más se recompensan con vistas al mar y a la isla de Tabarca.",
    de: "Ein geräumiges Apartment mit 110 m², 2024 komplett renoviert, ideal für 6–8 Personen. Nur 200 Meter vom Strand Levante und 7 Gehminuten vom Zentrum Santa Polas. Dritter Stock ohne Aufzug — ein paar Stufen extra belohnen mit Blick aufs Meer und die Insel Tabarca.",
    fr: "Appartement spacieux de 110 m², entièrement rénové en 2024, idéal pour 6–8 personnes. À 200 mètres de la plage Levante et à 7 minutes à pied du centre de Santa Pola. Troisième étage sans ascenseur : quelques marches de plus offrent une vue sur la mer et l’île de Tabarca.",
  },
  "apartment.p2": {
    cs: "Tři prostorné ložnice mají široké postele, pohodlné matrace a šatní skříně. K dispozici jsou dvě moderní koupelny se sprchou. Obývací pokoj s velkou TV a rozkládacím gaučem je místem k večernímu klidu. Z obýváku vejdete na terasu — sklenka vína s výhledem na moře.",
    en: "Three spacious bedrooms have wide beds, comfortable mattresses and wardrobes. There are two modern bathrooms with showers. The living room with a large TV and a sofa bed is for quiet evenings. From the living room you step onto the terrace — a glass of wine with a sea view.",
    es: "Tres dormitorios espaciosos con camas anchas, colchones cómodos y armarios. Hay dos baños modernos con ducha. El salón con televisor grande y sofá cama invita a las tardes tranquilas. Desde el salón se sale a la terraza: una copa de vino con vistas al mar.",
    de: "Drei geräumige Schlafzimmer mit breiten Betten, bequemen Matratzen und Schränken. Zwei moderne Bäder mit Dusche. Das Wohnzimmer mit großem Fernseher und Schlafsofa ist für ruhige Abende. Vom Wohnzimmer treten Sie auf die Terrasse — ein Glas Wein mit Meerblick.",
    fr: "Trois chambres spacieuses avec lits larges, matelas confortables et armoires. Deux salles de bain modernes avec douche. Le salon avec grand téléviseur et canapé-lit invite aux soirées calmes. Du salon, on passe à la terrasse — un verre de vin face à la mer.",
  },
  "apartment.p3": {
    cs: "Kuchyně je plně vybavena: myčka, mikrovlnná trouba, kávovar Nespresso a indukční deska. V celém bytě je rychlý internet, klimatizace, stropní ventilátor a pracovní místo pro ty, kdo občas pracují na dálku.",
    en: "The kitchen is fully equipped: dishwasher, microwave, Nespresso machine and induction hob. High-speed internet, air conditioning, a ceiling fan and a desk for remote work are available throughout.",
    es: "La cocina está completamente equipada: lavavajillas, microondas, cafetera Nespresso y placa de inducción. Hay internet rápido, aire acondicionado, ventilador de techo y un rincón de trabajo para quien teletrabaja.",
    de: "Die Küche ist vollständig ausgestattet: Spülmaschine, Mikrowelle, Nespresso-Maschine und Induktionskochfeld. Im ganzen Apartment gibt es schnelles Internet, Klimaanlage, Deckenventilator und einen Arbeitsplatz fürs Homeoffice.",
    fr: "La cuisine est entièrement équipée : lave-vaisselle, micro-ondes, machine Nespresso et plaque à induction. Internet haut débit, climatisation, ventilateur de plafond et un coin bureau pour le télétravail.",
  },
  "apartment.p4": {
    cs: "Najdete tu pračku, sušák, žehličku, žehlicí prkno a fén. Ideální volba pro rodiny i skupiny přátel, kteří hledají klid, komfort a výhled na moře.",
    en: "There is a washing machine, drying rack, iron, ironing board and hairdryer. An ideal choice for families and groups of friends looking for calm, comfort and a sea view.",
    es: "Hay lavadora, tendedero, plancha, tabla de planchar y secador. Una opción ideal para familias y grupos de amigos que buscan calma, confort y vistas al mar.",
    de: "Waschmaschine, Wäscheständer, Bügeleisen, Bügelbrett und Föhn sind vorhanden. Ideal für Familien und Freundesgruppen, die Ruhe, Komfort und Meerblick suchen.",
    fr: "Lave-linge, étendoir, fer, planche à repasser et sèche-cheveux sont à disposition. Un choix idéal pour les familles et les groupes d’amis en quête de calme, de confort et d’une vue mer.",
  },
  "apartment.amenityAc": { cs: "Klima", en: "A/C", es: "Aire", de: "Klima", fr: "Clim" },
  "apartment.amenityTv": { cs: "TV", en: "TV", es: "TV", de: "TV", fr: "TV" },
  "apartment.amenityWifi": { cs: "Wi-Fi", en: "Wi-Fi", es: "Wi-Fi", de: "WLAN", fr: "Wi-Fi" },
  "apartment.amenityCoffee": { cs: "Nespresso", en: "Nespresso", es: "Nespresso", de: "Nespresso", fr: "Nespresso" },
  "apartment.amenityTowels": { cs: "Osušky", en: "Towels", es: "Toallas", de: "Handtücher", fr: "Serviettes" },
  "apartment.amenityTransfer": { cs: "Transfer", en: "Transfer", es: "Transfer", de: "Transfer", fr: "Transfert" },
  "apartment.amenityHost": { cs: "Správce", en: "Caretaker", es: "Encargado", de: "Hausmeister", fr: "Gestionnaire" },
  "apartment.galleryTitle": {
    cs: "Procházka bytem",
    en: "A walk through the home",
    es: "Un paseo por el piso",
    de: "Rundgang durch die Wohnung",
    fr: "Promenade dans l’appartement",
  },
  "apartment.gallery.living": {
    cs: "Obývací pokoj",
    en: "Living room",
    es: "Salón",
    de: "Wohnzimmer",
    fr: "Salon",
  },
  "apartment.gallery.kitchen": { cs: "Kuchyně", en: "Kitchen", es: "Cocina", de: "Küche", fr: "Cuisine" },
  "apartment.gallery.terrace": {
    cs: "Terasa s výhledem na moře",
    en: "Terrace with sea view",
    es: "Terraza con vistas al mar",
    de: "Terrasse mit Meerblick",
    fr: "Terrasse avec vue mer",
  },
  "apartment.gallery.terraceSofa": {
    cs: "Posezení na terase",
    en: "Terrace seating",
    es: "Estar en la terraza",
    de: "Sitzplatz auf der Terrasse",
    fr: "Coin salon sur la terrasse",
  },
  "apartment.gallery.bedroom1": { cs: "Ložnice", en: "Bedroom", es: "Dormitorio", de: "Schlafzimmer", fr: "Chambre" },
  "apartment.gallery.bedroom2": {
    cs: "Ložnice s pracovním stolem",
    en: "Bedroom with desk",
    es: "Dormitorio con escritorio",
    de: "Schlafzimmer mit Schreibtisch",
    fr: "Chambre avec bureau",
  },
  "apartment.gallery.bath1": { cs: "Koupelna", en: "Bathroom", es: "Baño", de: "Bad", fr: "Salle de bain" },
  "apartment.gallery.bath2": {
    cs: "Druhá koupelna",
    en: "Second bathroom",
    es: "Segundo baño",
    de: "Zweites Bad",
    fr: "Deuxième salle de bain",
  },
  "apartment.addressTitle": { cs: "Kde bydlíte", en: "Where you stay", es: "Dónde se aloja", de: "Wo Sie wohnen", fr: "Où vous logez" },
  "apartment.noLift": {
    cs: "Třetí patro, budova bez výtahu.",
    en: "Third floor, no lift in the building.",
    es: "Tercer piso, edificio sin ascensor.",
    de: "Dritter Stock, kein Aufzug.",
    fr: "Troisième étage, immeuble sans ascenseur.",
  },

  "santaPola.metaTitle": {
    cs: "Santa Pola · Prázdniny ve Španělsku",
    en: "Santa Pola · Holidays in Spain",
    es: "Santa Pola · Vacaciones en España",
    de: "Santa Pola · Ferien in Spanien",
    fr: "Santa Pola · Vacances en Espagne",
  },
  "santaPola.title": {
    cs: "Santa Pola",
    en: "Santa Pola",
    es: "Santa Pola",
    de: "Santa Pola",
    fr: "Santa Pola",
  },
  "santaPola.lead": {
    cs: "Přímořské město na východním pobřeží Španělska, kousek od Alicante. Pláže s pozvolným vstupem, přístav, trhy a víc než 300 slunečných dní.",
    en: "A seaside town on Spain’s east coast, close to Alicante. Beaches with a gentle entry, a harbour, markets and more than 300 sunny days.",
    es: "Un pueblo costero en el este de España, cerca de Alicante. Playas de entrada suave, puerto, mercados y más de 300 días de sol.",
    de: "Ein Küstenort an Spaniens Ostküste, nahe Alicante. Strände mit sanftem Zugang, Hafen, Märkte und mehr als 300 Sonnentage.",
    fr: "Une ville balnéaire sur la côte est de l’Espagne, près d’Alicante. Plages à pente douce, port, marchés et plus de 300 jours de soleil.",
  },
  "santaPola.cityTitle": {
    cs: "Město, které dýchá mořem",
    en: "A town that breathes the sea",
    es: "Un pueblo que respira el mar",
    de: "Eine Stadt, die nach Meer duftet",
    fr: "Une ville qui respire la mer",
  },
  "santaPola.cityText": {
    cs: "Santa Pola má přibližně 38 500 obyvatel a historii sahající k Římanům. V létě je živější, v zimě tišší — ideální i mimo hlavní sezónu. Pro rodiny jsou tu hřiště i Pola Park.",
    en: "Santa Pola has about 38,500 residents and a history that reaches back to the Romans. Summers are livelier, winters quieter — lovely even off-season. Families will find playgrounds and Pola Park.",
    es: "Santa Pola tiene unos 38.500 habitantes y una historia que llega hasta los romanos. En verano late más, en invierno se aquieta: también es ideal fuera de temporada. Hay parques infantiles y Pola Park.",
    de: "Santa Pola hat rund 38.500 Einwohner und eine Geschichte bis zu den Römern. Im Sommer lebendiger, im Winter stiller — auch außerhalb der Hauptsaison schön. Für Familien gibt es Spielplätze und Pola Park.",
    fr: "Santa Pola compte environ 38 500 habitants et une histoire qui remonte aux Romains. Plus animée l’été, plus tranquille l’hiver — idéale aussi hors saison. Aires de jeux et Pola Park pour les familles.",
  },
  "santaPola.beachesTitle": { cs: "Pláže", en: "Beaches", es: "Playas", de: "Strände", fr: "Plages" },
  "santaPola.beachesText": {
    cs: "Platja de Llevant, Playa Varadero a Gran Playa leží v docházkové vzdálenosti. Promenáda zve k večerní chůzi, voda je ke koupání zhruba od května do října.",
    en: "Platja de Llevant, Playa Varadero and Gran Playa are within walking distance. The promenade is for evening walks; the sea is good for swimming from about May to October.",
    es: "Platja de Llevant, Playa Varadero y Gran Playa quedan a pie. El paseo invita a caminar al atardecer; el mar es bueno para bañarse de mayo a octubre aproximadamente.",
    de: "Platja de Llevant, Playa Varadero und Gran Playa sind zu Fuß erreichbar. Die Promenade lädt zum Abendspaziergang ein; zum Baden eignet sich das Meer etwa von Mai bis Oktober.",
    fr: "Platja de Llevant, Playa Varadero et Gran Playa sont accessibles à pied. La promenade invite à marcher le soir ; la mer se prête à la baignade d’environ mai à octobre.",
  },
  "santaPola.foodTitle": {
    cs: "Trhy a stůl",
    en: "Markets and the table",
    es: "Mercados y mesa",
    de: "Märkte und Tisch",
    fr: "Marchés et table",
  },
  "santaPola.foodText": {
    cs: "Každý týden dva trhy s ovocem, olivami a oblečením. V přístavu rybáři prodávají úlovek. Ochutnejte tapas, paellu, ryby a churros. Blízko domu jsou Mercadona, Carrefour i restaurace CataSimo, Tremenda a La Moruna.",
    en: "Two weekly markets with fruit, olives and clothes. At the harbour fishermen sell the catch. Try tapas, paella, fish and churros. Nearby you will find Mercadona, Carrefour and restaurants such as CataSimo, Tremenda and La Moruna.",
    es: "Dos mercadillos semanales con fruta, aceitunas y ropa. En el puerto los pescadores venden la captura. Pruebe tapas, paella, pescado y churros. Cerca hay Mercadona, Carrefour y restaurantes como CataSimo, Tremenda y La Moruna.",
    de: "Zwei Wochenmärkte mit Obst, Oliven und Kleidung. Am Hafen verkaufen Fischer den Fang. Probieren Sie Tapas, Paella, Fisch und Churros. In der Nähe: Mercadona, Carrefour und Restaurants wie CataSimo, Tremenda und La Moruna.",
    fr: "Deux marchés par semaine, fruits, olives et vêtements. Au port, les pêcheurs vendent la pêche. Goûtez tapas, paella, poisson et churros. Tout près : Mercadona, Carrefour et des restaurants comme CataSimo, Tremenda et La Moruna.",
  },
  "santaPola.tripsTitle": { cs: "Výlety", en: "Trips", es: "Excursiones", de: "Ausflüge", fr: "Excursions" },
  "santaPola.tripsText": {
    cs: "Solná jezera s plameňáky, Museo del Mar v pevnosti, akvárium Středozemního moře a Museo de la Sal. Alicante je 20 minut autem, Elche s palmovým hájem UNESCO 25 minut, Cartagena 1,5 hodiny, Valencie přibližně 2 hodiny.",
    en: "Salt lakes with flamingos, the Museo del Mar in the fortress, the Mediterranean aquarium and the Salt Museum. Alicante is 20 minutes by car, Elche with its UNESCO palm grove 25 minutes, Cartagena 1.5 hours, Valencia about 2 hours.",
    es: "Salinas con flamencos, Museo del Mar en la fortaleza, acuario del Mediterráneo y Museo de la Sal. Alicante está a 20 minutos en coche, Elche con su palmeral UNESCO a 25, Cartagena a 1,5 horas y Valencia a unas 2 horas.",
    de: "Salzseen mit Flamingos, Museo del Mar in der Festung, Mittelmeer-Aquarium und Salzmuseum. Alicante ist 20 Minuten mit dem Auto, Elche mit dem UNESCO-Palmenhain 25 Minuten, Cartagena 1,5 Stunden, Valencia etwa 2 Stunden.",
    fr: "Salines aux flamants, Museo del Mar dans la forteresse, aquarium méditerranéen et musée du sel. Alicante est à 20 minutes en voiture, Elche et sa palmeraie UNESCO à 25 minutes, Carthagène à 1 h 30, Valence à environ 2 heures.",
  },
  "santaPola.tabarcaTitle": {
    cs: "Ostrov Tabarca",
    en: "Tabarca Island",
    es: "Isla de Tabarca",
    de: "Insel Tabarca",
    fr: "Île de Tabarca",
  },
  "santaPola.tabarcaText": {
    cs: "Nejmenší trvale obydlený ostrov Španělska. Lodě vyplouvají z přístavu, plavba trvá asi 25 minut. Pláže, úzké uličky a den na moři.",
    en: "The smallest inhabited island in Spain. Boats leave from the harbour; the crossing takes about 25 minutes. Beaches, narrow streets and a day on the water.",
    es: "La isla habitada más pequeña de España. Los barcos salen del puerto; la travesía dura unos 25 minutos. Playas, callejuelas y un día en el mar.",
    de: "Spaniens kleinste dauerhaft bewohnte Insel. Boote legen im Hafen ab, die Überfahrt dauert etwa 25 Minuten. Strände, Gassen und ein Tag auf dem Wasser.",
    fr: "La plus petite île habitée d’Espagne. Les bateaux partent du port ; la traversée dure environ 25 minutes. Plages, ruelles et une journée en mer.",
  },

  "pricing.metaTitle": {
    cs: "Ceník · Prázdniny ve Španělsku",
    en: "Rates · Holidays in Spain",
    es: "Tarifas · Vacaciones en España",
    de: "Preise · Ferien in Spanien",
    fr: "Tarifs · Vacances en Espagne",
  },
  "pricing.title": { cs: "Ceník", en: "Rates", es: "Tarifas", de: "Preise", fr: "Tarifs" },
  "pricing.lead": {
    cs: "Cena za noc podle sezóny. K pobytu se přičítá závěrečný úklid. Záloha 50 % při potvrzení, doplatek 30 dní před příjezdem.",
    en: "Nightly rate by season. Final cleaning is added to the stay. 50% deposit on confirmation, balance 30 days before arrival.",
    es: "Precio por noche según temporada. Se suma la limpieza final. Señal del 50 % al confirmar, resto 30 días antes de la llegada.",
    de: "Nachtpreis nach Saison. Endreinigung kommt zum Aufenthalt hinzu. 50 % Anzahlung bei Bestätigung, Rest 30 Tage vor Anreise.",
    fr: "Tarif par nuit selon la saison. Le ménage de fin de séjour s’ajoute. Acompte de 50 % à la confirmation, solde 30 jours avant l’arrivée.",
  },
  "pricing.perNight": { cs: "/ noc", en: "/ night", es: "/ noche", de: "/ Nacht", fr: "/ nuit" },
  "pricing.minNights": {
    cs: "minimálně {n} noci",
    en: "minimum {n} nights",
    es: "mínimo {n} noches",
    de: "mindestens {n} Nächte",
    fr: "minimum {n} nuits",
  },
  "pricing.includedTitle": {
    cs: "Cena zahrnuje",
    en: "The price includes",
    es: "El precio incluye",
    de: "Im Preis enthalten",
    fr: "Le tarif comprend",
  },
  "pricing.included": {
    cs: "ubytování\nuvítací balíček\nručník, osuška a ložní prádlo pro každého\nWi-Fi a TV\nmístní správce 24 hodin denně (EN, ES, NL)\nprostředky do kuchyně a koupelny\nmístní daně a poplatky",
    en: "accommodation\nwelcome pack\ntowel, beach towel and bed linen for each guest\nWi-Fi and TV\nlocal caretaker 24/7 (EN, ES, NL)\nkitchen and bathroom supplies\nlocal taxes and fees",
    es: "alojamiento\npack de bienvenida\ntoalla, toalla de playa y ropa de cama para cada huésped\nWi-Fi y TV\nencargado local 24 h (EN, ES, NL)\nproductos de cocina y baño\nimpuestos y tasas locales",
    de: "Unterkunft\nWillkommenspaket\nHandtuch, Strandtuch und Bettwäsche für jeden Gast\nWLAN und TV\nlokaler Hausmeister rund um die Uhr (EN, ES, NL)\nKüchen- und Badbedarf\nlokale Steuern und Gebühren",
    fr: "hébergement\npanier de bienvenue\nserviette, serviette de plage et linge de lit pour chaque hôte\nWi-Fi et TV\ngestionnaire local 24 h/24 (EN, ES, NL)\nproduits de cuisine et de salle de bain\ntaxes et frais locaux",
  },
  "pricing.extrasTitle": {
    cs: "Příplatky",
    en: "Extras",
    es: "Suplementos",
    de: "Zusatzkosten",
    fr: "Suppléments",
  },
  "pricing.cleaningLabel": {
    cs: "Závěrečný úklid",
    en: "Final cleaning",
    es: "Limpieza final",
    de: "Endreinigung",
    fr: "Ménage de fin de séjour",
  },
  "pricing.transferLabel": {
    cs: "Transfer z letiště s česky hovořícím řidičem (1 cesta, max. 4 osoby)",
    en: "Airport transfer with a Czech-speaking driver (one way, max. 4 people)",
    es: "Transfer desde el aeropuerto con conductor de habla checa (un trayecto, máx. 4 personas)",
    de: "Flughafentransfer mit tschechischsprachigem Fahrer (einfache Fahrt, max. 4 Personen)",
    fr: "Transfert aéroport avec chauffeur parlant tchèque (aller simple, max. 4 personnes)",
  },
  "pricing.longStayLabel": {
    cs: "Sleva při pobytu 30 a více dní",
    en: "Discount for stays of 30 days or more",
    es: "Descuento en estancias de 30 días o más",
    de: "Rabatt ab 30 Übernachtungen",
    fr: "Réduction dès 30 nuits",
  },
  "pricing.termsTitle": {
    cs: "Platba a storno",
    en: "Payment and cancellation",
    es: "Pago y cancelación",
    de: "Zahlung und Storno",
    fr: "Paiement et annulation",
  },
  "pricing.terms": {
    cs: "Záloha 50 % při rezervaci, doplatek 30 dní před začátkem pobytu.\nStorno 60 dní před příjezdem: 25 %.\nStorno 30 dní před příjezdem: 50 %.\nStorno 21 dní před příjezdem: 100 %.",
    en: "50% deposit on booking, balance 30 days before arrival.\nCancellation 60 days before arrival: 25%.\nCancellation 30 days before arrival: 50%.\nCancellation 21 days before arrival: 100%.",
    es: "Señal del 50 % al reservar, resto 30 días antes de la llegada.\nCancelación 60 días antes: 25 %.\nCancelación 30 días antes: 50 %.\nCancelación 21 días antes: 100 %.",
    de: "50 % Anzahlung bei Buchung, Rest 30 Tage vor Anreise.\nStorno 60 Tage vorher: 25 %.\nStorno 30 Tage vorher: 50 %.\nStorno 21 Tage vorher: 100 %.",
    fr: "Acompte de 50 % à la réservation, solde 30 jours avant l’arrivée.\nAnnulation 60 jours avant : 25 %.\nAnnulation 30 jours avant : 50 %.\nAnnulation 21 jours avant : 100 %.",
  },
  "pricing.licence": {
    cs: "Turistická licence Comunitat Valenciana VT-502018-A.",
    en: "Tourist licence Comunitat Valenciana VT-502018-A.",
    es: "Licencia turística Comunitat Valenciana VT-502018-A.",
    de: "Tourismuslizenz Comunitat Valenciana VT-502018-A.",
    fr: "Licence touristique Comunitat Valenciana VT-502018-A.",
  },
  "pricing.season.winter": { cs: "Zima", en: "Winter", es: "Invierno", de: "Winter", fr: "Hiver" },
  "pricing.season.spring": { cs: "Jaro", en: "Spring", es: "Primavera", de: "Frühling", fr: "Printemps" },
  "pricing.season.summer": { cs: "Léto", en: "Summer", es: "Verano", de: "Sommer", fr: "Été" },
  "pricing.season.autumn": { cs: "Podzim", en: "Autumn", es: "Otoño", de: "Herbst", fr: "Automne" },
  "pricing.month.1": { cs: "Leden", en: "January", es: "Enero", de: "Januar", fr: "Janvier" },
  "pricing.month.2": { cs: "Únor", en: "February", es: "Febrero", de: "Februar", fr: "Février" },
  "pricing.month.3": { cs: "Březen", en: "March", es: "Marzo", de: "März", fr: "Mars" },
  "pricing.month.4": { cs: "Duben", en: "April", es: "Abril", de: "April", fr: "Avril" },
  "pricing.month.5": { cs: "Květen", en: "May", es: "Mayo", de: "Mai", fr: "Mai" },
  "pricing.month.6": { cs: "Červen", en: "June", es: "Junio", de: "Juni", fr: "Juin" },
  "pricing.month.7": { cs: "Červenec", en: "July", es: "Julio", de: "Juli", fr: "Juillet" },
  "pricing.month.8": { cs: "Srpen", en: "August", es: "Agosto", de: "August", fr: "Août" },
  "pricing.month.9": { cs: "Září", en: "September", es: "Septiembre", de: "September", fr: "Septembre" },
  "pricing.month.10": { cs: "Říjen", en: "October", es: "Octubre", de: "Oktober", fr: "Octobre" },
  "pricing.month.11": { cs: "Listopad", en: "November", es: "Noviembre", de: "November", fr: "Novembre" },
  "pricing.month.12": { cs: "Prosinec", en: "December", es: "Diciembre", de: "Dezember", fr: "Décembre" },

  "rates.1": { _: "70" },
  "rates.2": { _: "70" },
  "rates.3": { _: "80" },
  "rates.4": { _: "80" },
  "rates.5": { _: "95" },
  "rates.6": { _: "140" },
  "rates.7": { _: "185" },
  "rates.8": { _: "185" },
  "rates.9": { _: "110" },
  "rates.10": { _: "80" },
  "rates.11": { _: "70" },
  "rates.12": { _: "70" },
  "rates.min.1": { _: "3" },
  "rates.min.2": { _: "3" },
  "rates.min.3": { _: "3" },
  "rates.min.4": { _: "3" },
  "rates.min.5": { _: "5" },
  "rates.min.6": { _: "5" },
  "rates.min.7": { _: "5" },
  "rates.min.8": { _: "5" },
  "rates.min.9": { _: "5" },
  "rates.min.10": { _: "3" },
  "rates.min.11": { _: "3" },
  "rates.min.12": { _: "3" },
  "rates.cleaning": { _: "110" },
  "rates.transfer": { _: "30" },
  "rates.longStayDiscount": { _: "10" },

  "booking.metaTitle": {
    cs: "Rezervace · Prázdniny ve Španělsku",
    en: "Booking · Holidays in Spain",
    es: "Reserva · Vacaciones en España",
    de: "Buchung · Ferien in Spanien",
    fr: "Réservation · Vacances en Espagne",
  },
  "booking.title": { cs: "Rezervace", en: "Booking", es: "Reserva", de: "Buchung", fr: "Réservation" },
  "booking.lead": {
    cs: "Vyberte volné dny a pošlete nezávaznou poptávku. Ozveme se a po dohodě pošleme odkaz na zálohu 50 %.",
    en: "Choose free dates and send a non-binding enquiry. We will reply and, once agreed, send a link for the 50% deposit.",
    es: "Elija días libres y envíe una consulta sin compromiso. Responderemos y, al acordar, enviaremos el enlace de la señal del 50 %.",
    de: "Wählen Sie freie Tage und senden Sie eine unverbindliche Anfrage. Wir antworten und schicken nach Absprache den Link für 50 % Anzahlung.",
    fr: "Choisissez des jours libres et envoyez une demande sans engagement. Nous répondrons et, une fois d’accord, enverrons le lien d’acompte de 50 %.",
  },
  "booking.from": { cs: "Příjezd", en: "Arrival", es: "Llegada", de: "Anreise", fr: "Arrivée" },
  "booking.to": { cs: "Odjezd", en: "Departure", es: "Salida", de: "Abreise", fr: "Départ" },
  "booking.guests": { cs: "Počet osob", en: "Guests", es: "Personas", de: "Personen", fr: "Personnes" },
  "booking.name": { cs: "Jméno", en: "Name", es: "Nombre", de: "Name", fr: "Nom" },
  "booking.email": { cs: "E-mail", en: "Email", es: "Correo", de: "E-Mail", fr: "E-mail" },
  "booking.message": { cs: "Zpráva", en: "Message", es: "Mensaje", de: "Nachricht", fr: "Message" },
  "booking.transfer": {
    cs: "Mám zájem o transfer z letiště",
    en: "I would like an airport transfer",
    es: "Me interesa el transfer del aeropuerto",
    de: "Ich möchte einen Flughafentransfer",
    fr: "Je souhaite un transfert aéroport",
  },
  "booking.submit": {
    cs: "Odeslat poptávku",
    en: "Send enquiry",
    es: "Enviar consulta",
    de: "Anfrage senden",
    fr: "Envoyer la demande",
  },
  "booking.success": {
    cs: "Děkujeme. Poptávku jsme dostali a ozveme se e-mailem.",
    en: "Thank you. We have received your enquiry and will reply by email.",
    es: "Gracias. Hemos recibido la consulta y responderemos por correo.",
    de: "Danke. Wir haben Ihre Anfrage erhalten und antworten per E-Mail.",
    fr: "Merci. Nous avons bien reçu votre demande et répondrons par e-mail.",
  },
  "booking.error": {
    cs: "Poptávku se nepodařilo odeslat. Zkuste to znovu nebo napište na info@prazdninyvespanelsku.cz.",
    en: "Could not send the enquiry. Please try again or write to info@prazdninyvespanelsku.cz.",
    es: "No se pudo enviar. Inténtelo de nuevo o escriba a info@prazdninyvespanelsku.cz.",
    de: "Die Anfrage konnte nicht gesendet werden. Bitte erneut versuchen oder an info@prazdninyvespanelsku.cz schreiben.",
    fr: "Impossible d’envoyer la demande. Réessayez ou écrivez à info@prazdninyvespanelsku.cz.",
  },
  "booking.occupied": {
    cs: "Tyto dny už nejsou volné.",
    en: "These dates are no longer free.",
    es: "Esas fechas ya no están libres.",
    de: "Diese Tage sind nicht mehr frei.",
    fr: "Ces dates ne sont plus libres.",
  },
  "booking.minNightsError": {
    cs: "V tomto období je minimum {n} nocí.",
    en: "The minimum stay in this period is {n} nights.",
    es: "En este periodo el mínimo es de {n} noches.",
    de: "In diesem Zeitraum sind mindestens {n} Nächte nötig.",
    fr: "Le séjour minimum sur cette période est de {n} nuits.",
  },
  "booking.nights": { cs: "nocí", en: "nights", es: "noches", de: "Nächte", fr: "nuits" },
  "booking.stay": { cs: "Ubytování", en: "Stay", es: "Alojamiento", de: "Unterkunft", fr: "Séjour" },
  "booking.total": { cs: "Celkem", en: "Total", es: "Total", de: "Gesamt", fr: "Total" },
  "booking.deposit": {
    cs: "Záloha 50 %",
    en: "50% deposit",
    es: "Señal 50 %",
    de: "50 % Anzahlung",
    fr: "Acompte 50 %",
  },
  "booking.legendFree": { cs: "Volno", en: "Free", es: "Libre", de: "Frei", fr: "Libre" },
  "booking.legendBusy": { cs: "Obsazeno", en: "Occupied", es: "Ocupado", de: "Belegt", fr: "Occupé" },
  "booking.faqTitle": {
    cs: "Časté dotazy",
    en: "Frequently asked questions",
    es: "Preguntas frecuentes",
    de: "Häufige Fragen",
    fr: "Questions fréquentes",
  },

  "faq.q1": {
    cs: "Odkud mohu letět do Alicante a jaká je cena letenky?",
    en: "Where can I fly to Alicante from, and what do tickets cost?",
    es: "¿Desde dónde puedo volar a Alicante y cuánto cuesta el billete?",
    de: "Woher kann ich nach Alicante fliegen und was kostet das Ticket?",
    fr: "D’où puis-je voler vers Alicante et quel est le prix du billet ?",
  },
  "faq.a1": {
    cs: "Přímé lety jsou z Prahy, Pardubic, Norimberku, Lince, Katowic a Vídně. Ceny letenek se pohybují od 50 EUR. S nákupem rádi poradíme.",
    en: "Direct flights run from Prague, Pardubice, Nuremberg, Linz, Katowice and Vienna. Fares start around 50 EUR. We are happy to help with tickets.",
    es: "Hay vuelos directos desde Praga, Pardubice, Núremberg, Linz, Katowice y Viena. Los billetes empiezan en unos 50 EUR. Le ayudamos con la compra.",
    de: "Direktflüge gibt es aus Prag, Pardubice, Nürnberg, Linz, Katowice und Wien. Tickets ab etwa 50 EUR. Beim Kauf helfen wir gern.",
    fr: "Des vols directs existent depuis Prague, Pardubice, Nuremberg, Linz, Katowice et Vienne. Les billets commencent vers 50 EUR. Nous aidons volontiers à l’achat.",
  },
  "faq.q2": {
    cs: "Jak se do apartmánu dostanu z letiště?",
    en: "How do I get from the airport to the apartment?",
    es: "¿Cómo llego del aeropuerto al apartamento?",
    de: "Wie komme ich vom Flughafen zum Apartment?",
    fr: "Comment rejoindre l’appartement depuis l’aéroport ?",
  },
  "faq.a2": {
    cs: "Můžete jet taxíkem nebo Uberem, případně vám zajistíme transfer s česky hovořícím řidičem. Jedna cesta je kolem 30 EUR.",
    en: "You can take a taxi or Uber, or we can arrange a transfer with a Czech-speaking driver. One way is about 30 EUR.",
    es: "Puede tomar un taxi o Uber, o le organizamos un transfer con conductor de habla checa. Un trayecto ronda los 30 EUR.",
    de: "Sie können Taxi oder Uber nehmen, oder wir organisieren einen Transfer mit tschechischsprachigem Fahrer. Eine Strecke kostet etwa 30 EUR.",
    fr: "Vous pouvez prendre un taxi ou Uber, ou nous organisons un transfert avec un chauffeur parlant tchèque. Un trajet coûte environ 30 EUR.",
  },
  "faq.q3": {
    cs: "Jak daleko je apartmán od pláže?",
    en: "How far is the apartment from the beach?",
    es: "¿A qué distancia está la playa?",
    de: "Wie weit ist der Strand?",
    fr: "À quelle distance est la plage ?",
  },
  "faq.a3": {
    cs: "Pouhých 200 metrů (asi 3 minuty chůze) od pláže Playa Levante.",
    en: "Just 200 metres (about a 3-minute walk) from Playa Levante.",
    es: "Solo 200 metros (unos 3 minutos a pie) de Playa Levante.",
    de: "Nur 200 Meter (etwa 3 Gehminuten) vom Strand Playa Levante.",
    fr: "Seulement 200 mètres (environ 3 minutes à pied) de Playa Levante.",
  },
  "faq.q4": {
    cs: "Je v budově výtah?",
    en: "Is there a lift?",
    es: "¿Hay ascensor?",
    de: "Gibt es einen Aufzug?",
    fr: "Y a-t-il un ascenseur ?",
  },
  "faq.a4": {
    cs: "Ne, apartmán je ve třetím patře bez výtahu. Odměnou je klid a výhled na moře.",
    en: "No, the apartment is on the third floor without a lift. The reward is quiet and a sea view.",
    es: "No, el apartamento está en un tercer piso sin ascensor. La recompensa es la calma y las vistas al mar.",
    de: "Nein, das Apartment liegt im dritten Stock ohne Aufzug. Dafür gibt es Ruhe und Meerblick.",
    fr: "Non, l’appartement est au troisième étage sans ascenseur. La récompense : le calme et la vue mer.",
  },
  "faq.q5": {
    cs: "Kolik osob může v apartmánu bydlet?",
    en: "How many people can stay?",
    es: "¿Cuántas personas pueden alojarse?",
    de: "Wie viele Personen können wohnen?",
    fr: "Combien de personnes peuvent loger ?",
  },
  "faq.a5": {
    cs: "Ideálně 6 až 8 osob. Tři ložnice a rozkládací gauč v obývacím pokoji.",
    en: "Ideally 6 to 8 guests. Three bedrooms and a sofa bed in the living room.",
    es: "Idealmente 6 a 8 personas. Tres dormitorios y un sofá cama en el salón.",
    de: "Ideal 6 bis 8 Personen. Drei Schlafzimmer und ein Schlafsofa im Wohnzimmer.",
    fr: "Idéalement 6 à 8 personnes. Trois chambres et un canapé-lit dans le salon.",
  },
  "faq.q6": {
    cs: "Mohu si pronajmout jen jednu ložnici?",
    en: "Can I rent just one bedroom?",
    es: "¿Puedo alquilar solo un dormitorio?",
    de: "Kann ich nur ein Schlafzimmer mieten?",
    fr: "Puis-je louer une seule chambre ?",
  },
  "faq.a6": {
    cs: "Ne, apartmán pronajímáme pouze celý.",
    en: "No, we only rent the apartment as a whole.",
    es: "No, el apartamento se alquila entero.",
    de: "Nein, wir vermieten nur die gesamte Wohnung.",
    fr: "Non, l’appartement se loue uniquement en entier.",
  },
  "faq.q7": {
    cs: "Je v apartmánu Wi-Fi?",
    en: "Is there Wi-Fi?",
    es: "¿Hay Wi-Fi?",
    de: "Gibt es WLAN?",
    fr: "Y a-t-il le Wi-Fi ?",
  },
  "faq.a7": {
    cs: "Ano, vysokorychlostní optický internet zdarma, vhodný i pro práci na dálku.",
    en: "Yes, free high-speed fibre internet, suitable for remote work.",
    es: "Sí, internet de fibra de alta velocidad gratis, también para teletrabajar.",
    de: "Ja, kostenloses schnelles Glasfaser-Internet, auch fürs Homeoffice.",
    fr: "Oui, internet fibre haut débit gratuit, aussi pour le télétravail.",
  },
  "faq.q8": {
    cs: "Jaké vybavení má kuchyň?",
    en: "What kitchen equipment is there?",
    es: "¿Qué hay en la cocina?",
    de: "Wie ist die Küche ausgestattet?",
    fr: "Que contient la cuisine ?",
  },
  "faq.a8": {
    cs: "Chladnička, myčka, trouba, indukce, mikrovlnka, Nespresso, konvice, toustovač a nádobí v dostatečném množství.",
    en: "Fridge, dishwasher, oven, induction hob, microwave, Nespresso, kettle, toaster and plenty of crockery.",
    es: "Nevera, lavavajillas, horno, inducción, microondas, Nespresso, hervidor, tostadora y vajilla de sobra.",
    de: "Kühlschrank, Spülmaschine, Backofen, Induktion, Mikrowelle, Nespresso, Wasserkocher, Toaster und ausreichend Geschirr.",
    fr: "Réfrigérateur, lave-vaisselle, four, induction, micro-ondes, Nespresso, bouilloire, grille-pain et vaisselle en quantité.",
  },
  "faq.q9": {
    cs: "Jsou v apartmánu ručníky a ložní prádlo?",
    en: "Are towels and bed linen provided?",
    es: "¿Hay toallas y ropa de cama?",
    de: "Gibt es Handtücher und Bettwäsche?",
    fr: "Y a-t-il serviettes et linge de lit ?",
  },
  "faq.a9": {
    cs: "Ano, čisté ručníky, osušky a ložní prádlo jsou připraveny bez příplatku.",
    en: "Yes, clean towels, beach towels and bed linen are ready at no extra charge.",
    es: "Sí, toallas, toallas de playa y ropa de cama limpias sin recargo.",
    de: "Ja, saubere Handtücher, Strandtücher und Bettwäsche ohne Aufpreis.",
    fr: "Oui, serviettes, serviettes de plage et linge de lit propres sans supplément.",
  },
  "faq.q10": {
    cs: "Je v apartmánu pračka?",
    en: "Is there a washing machine?",
    es: "¿Hay lavadora?",
    de: "Gibt es eine Waschmaschine?",
    fr: "Y a-t-il une machine à laver ?",
  },
  "faq.a10": {
    cs: "Ano, pračka, sušák na prádlo a žehlička.",
    en: "Yes, a washing machine, drying rack and iron.",
    es: "Sí, lavadora, tendedero y plancha.",
    de: "Ja, Waschmaschine, Wäscheständer und Bügeleisen.",
    fr: "Oui, lave-linge, étendoir et fer à repasser.",
  },
  "faq.q11": {
    cs: "Je k dispozici dětská postýlka?",
    en: "Is a travel cot available?",
    es: "¿Hay cuna?",
    de: "Gibt es ein Babybett?",
    fr: "Y a-t-il un lit bébé ?",
  },
  "faq.a11": {
    cs: "Ano, na vyžádání připravíme rozkládací dětskou postýlku. Dejte nám vědět před příjezdem.",
    en: "Yes, we can prepare a folding travel cot on request. Please let us know before arrival.",
    es: "Sí, podemos preparar una cuna plegable si avisa antes de llegar.",
    de: "Ja, auf Wunsch stellen wir ein klappbares Babybett bereit. Bitte vor der Anreise Bescheid geben.",
    fr: "Oui, nous pouvons préparer un lit parapluie sur demande. Prévenez-nous avant l’arrivée.",
  },
  "faq.q12": {
    cs: "Jaké možnosti parkování jsou k dispozici?",
    en: "What parking is available?",
    es: "¿Dónde se puede aparcar?",
    de: "Welche Parkmöglichkeiten gibt es?",
    fr: "Où peut-on se garer ?",
  },
  "faq.a12": {
    cs: "V okolí budovy lze parkovat zdarma na veřejných místech.",
    en: "Free public parking is available around the building.",
    es: "Se puede aparcar gratis en la calle alrededor del edificio.",
    de: "Rund ums Haus gibt es kostenlose öffentliche Parkplätze.",
    fr: "Stationnement public gratuit autour de l’immeuble.",
  },
  "faq.q13": {
    cs: "Jaké aktivity nabízí Santa Pola a okolí?",
    en: "What is there to do in Santa Pola?",
    es: "¿Qué se puede hacer en Santa Pola?",
    de: "Was kann man in Santa Pola unternehmen?",
    fr: "Que faire à Santa Pola ?",
  },
  "faq.a13": {
    cs: "Koupání, promenáda, přístav a trhy. Rodiny ocení akvárium, Pola Park nebo loď na Tabarcu.",
    en: "Swimming, the promenade, the harbour and markets. Families enjoy the aquarium, Pola Park or a boat to Tabarca.",
    es: "Baño, paseo, puerto y mercados. Las familias disfrutan del acuario, Pola Park o el barco a Tabarca.",
    de: "Baden, Promenade, Hafen und Märkte. Familien mögen das Aquarium, Pola Park oder das Boot nach Tabarca.",
    fr: "Baignade, promenade, port et marchés. Les familles aiment l’aquarium, Pola Park ou le bateau vers Tabarca.",
  },
  "faq.q14": {
    cs: "Jaké jsou možnosti nakupování a restaurací?",
    en: "What about shopping and restaurants?",
    es: "¿Compras y restaurantes?",
    de: "Einkaufen und Restaurants?",
    fr: "Courses et restaurants ?",
  },
  "faq.a14": {
    cs: "V docházkové vzdálenosti supermarkety (nejbližší je na dohled od domu), obchody i restaurace s mořskými plody i španělskou kuchyní.",
    en: "Supermarkets (the nearest is in sight of the house), shops and restaurants with seafood, Spanish and international cooking are within walking distance.",
    es: "Supermercados (el más cercano se ve desde casa), tiendas y restaurantes de marisco, cocina española e internacional a pie.",
    de: "Supermärkte (der nächste ist vom Haus aus zu sehen), Läden und Restaurants mit Meeresfrüchten, spanischer und internationaler Küche sind zu Fuß erreichbar.",
    fr: "Supermarchés (le plus proche est visible depuis la maison), commerces et restaurants de fruits de mer, cuisine espagnole et internationale à pied.",
  },
  "faq.q15": {
    cs: "Jak probíhá check-in a check-out?",
    en: "How do check-in and check-out work?",
    es: "¿Cómo es el check-in y el check-out?",
    de: "Wie laufen Check-in und Check-out?",
    fr: "Comment se passent le check-in et le check-out ?",
  },
  "faq.a15": {
    cs: "Check-in od 16:00, check-out do 11:00. Klíče předává místní správce, který vás bytem provede. Detaily pošleme před příjezdem.",
    en: "Check-in from 16:00, check-out by 11:00. Keys are handed over by the local caretaker, who will show you around. Details are sent before arrival.",
    es: "Entrada desde las 16:00, salida hasta las 11:00. Las llaves las entrega el encargado local, que le enseña el piso. Los detalles se envían antes de llegar.",
    de: "Check-in ab 16:00, Check-out bis 11:00. Schlüssel übergibt der lokale Hausmeister und zeigt die Wohnung. Details kommen vor der Anreise.",
    fr: "Arrivée à partir de 16 h, départ avant 11 h. Les clés sont remises par le gestionnaire local, qui vous fait visiter. Les détails arrivent avant le séjour.",
  },
  "faq.q16": {
    cs: "Jaké je počasí v Santa Pole během roku?",
    en: "What is the weather like through the year?",
    es: "¿Cómo es el clima durante el año?",
    de: "Wie ist das Wetter im Jahresverlauf?",
    fr: "Quel temps fait-il dans l’année ?",
  },
  "faq.a16": {
    cs: "Středomořské klima s více než 300 slunečnými dny. Léta jsou horká, zimy mírné. Moře je ke koupání od začátku května do konce října.",
    en: "Mediterranean climate with more than 300 sunny days. Summers are hot, winters mild. The sea is good for swimming from early May to late October.",
    es: "Clima mediterráneo con más de 300 días de sol. Veranos calurosos, inviernos suaves. El mar es bueno para bañarse de mayo a finales de octubre.",
    de: "Mediterranes Klima mit über 300 Sonnentagen. Sommer heiß, Winter mild. Zum Baden eignet sich das Meer von Anfang Mai bis Ende Oktober.",
    fr: "Climat méditerranéen avec plus de 300 jours de soleil. Étés chauds, hivers doux. La mer se prête à la baignade de début mai à fin octobre.",
  },
  "faq.q17": {
    cs: "Jak se dostanu na ostrov Tabarca?",
    en: "How do I get to Tabarca Island?",
    es: "¿Cómo llego a Tabarca?",
    de: "Wie komme ich nach Tabarca?",
    fr: "Comment aller à Tabarca ?",
  },
  "faq.a17": {
    cs: "Lodě odplouvají pravidelně z přístavu Santa Pola. Plavba trvá přibližně 25 minut.",
    en: "Boats leave regularly from Santa Pola harbour. The crossing takes about 25 minutes.",
    es: "Los barcos salen con regularidad del puerto de Santa Pola. La travesía dura unos 25 minutos.",
    de: "Boote fahren regelmäßig vom Hafen Santa Pola. Die Überfahrt dauert etwa 25 Minuten.",
    fr: "Les bateaux partent régulièrement du port de Santa Pola. La traversée dure environ 25 minutes.",
  },
  "faq.q18": {
    cs: "Jak daleko jsou zajímavá města v okolí?",
    en: "How far are nearby towns?",
    es: "¿A qué distancia están otras ciudades?",
    de: "Wie weit sind andere Städte?",
    fr: "À quelle distance sont les villes autour ?",
  },
  "faq.a18": {
    cs: "Alicante 20 minut autem, Elche 25 minut, Cartagena 1,5 hodiny, Valencie přibližně 2 hodiny. Rychlovlakem jste z Alicante v Madridu za 2,5 hodiny.",
    en: "Alicante 20 minutes by car, Elche 25 minutes, Cartagena 1.5 hours, Valencia about 2 hours. High-speed trains from Alicante reach Madrid in 2.5 hours.",
    es: "Alicante a 20 minutos en coche, Elche a 25, Cartagena a 1,5 horas y Valencia a unas 2 horas. El AVE desde Alicante llega a Madrid en 2,5 horas.",
    de: "Alicante 20 Minuten mit dem Auto, Elche 25 Minuten, Cartagena 1,5 Stunden, Valencia etwa 2 Stunden. Mit dem Hochgeschwindigkeitszug sind Sie von Alicante in 2,5 Stunden in Madrid.",
    fr: "Alicante à 20 minutes en voiture, Elche à 25 minutes, Carthagène à 1 h 30, Valence à environ 2 heures. Le train à grande vitesse relie Alicante à Madrid en 2 h 30.",
  },

  "contact.metaTitle": {
    cs: "Kontakt · Prázdniny ve Španělsku",
    en: "Contact · Holidays in Spain",
    es: "Contacto · Vacaciones en España",
    de: "Kontakt · Ferien in Spanien",
    fr: "Contact · Vacances en Espagne",
  },
  "contact.title": { cs: "Kontakt", en: "Contact", es: "Contacto", de: "Kontakt", fr: "Contact" },
  "contact.lead": {
    cs: "Jmenuji se Marian a Španělsko je pro mě srdeční záležitost. Už několik let zde trávím volný čas — moře, slunce a místní pohostinnost. Proto nabízím apartmán i dalším cestovatelům, kteří chtějí poznat Costa Blancu a cítit se jako doma.\n\nDbám na čistotu, pohodlí i drobnosti, které zpříjemní pobyt. Rád poradím s výlety, restauracemi i skrytými místy. Cílem je, aby pobyt nebyl jen ubytováním, ale zážitkem, na který budete rádi vzpomínat.",
    en: "My name is Marian and Spain is close to my heart. I have spent my free time here for years — sea, sun and local hospitality. That is why I offer the apartment to travellers who want to know the Costa Blanca and feel at home.\n\nI care about cleanliness, comfort and the small things that make a stay kinder. I am glad to advise on trips, restaurants and hidden places. The aim is a stay you will remember, not just a booking.",
    es: "Me llamo Marian y España me llega al corazón. Llevo años pasando aquí el tiempo libre: mar, sol y hospitalidad. Por eso ofrezco el apartamento a viajeros que quieran conocer la Costa Blanca y sentirse como en casa.\n\nCuidamos la limpieza, el confort y los detalles. Encantado de aconsejar sobre excursiones, restaurantes y rincones. El objetivo es un recuerdo, no solo un alojamiento.",
    de: "Ich heiße Marian, und Spanien liegt mir am Herzen. Seit Jahren verbringe ich hier meine freie Zeit — Meer, Sonne und Gastfreundschaft. Deshalb biete ich das Apartment Reisenden an, die die Costa Blanca kennenlernen und sich wie zu Hause fühlen möchten.\n\nMir liegen Sauberkeit, Komfort und kleine Gesten am Herzen. Gerne berate ich zu Ausflügen, Restaurants und versteckten Orten. Ziel ist eine Erinnerung, nicht nur eine Unterkunft.",
    fr: "Je m’appelle Marian et l’Espagne me tient à cœur. J’y passe mon temps libre depuis des années — mer, soleil et hospitalité. C’est pourquoi je propose l’appartement à ceux qui veulent découvrir la Costa Blanca et se sentir chez eux.\n\nJe veille à la propreté, au confort et aux petits gestes. Je conseille volontiers sorties, restaurants et coins discrets. L’objectif : un souvenir, pas seulement un logement.",
  },
  "contact.formTitle": {
    cs: "Napište nám",
    en: "Write to us",
    es: "Escríbanos",
    de: "Schreiben Sie uns",
    fr: "Écrivez-nous",
  },
  "contact.submit": {
    cs: "Odeslat zprávu",
    en: "Send message",
    es: "Enviar mensaje",
    de: "Nachricht senden",
    fr: "Envoyer le message",
  },
  "contact.success": {
    cs: "Zpráva odešla, ozveme se.",
    en: "Message sent, we will get back to you.",
    es: "Mensaje enviado, le responderemos.",
    de: "Nachricht gesendet, wir melden uns.",
    fr: "Message envoyé, nous vous répondrons.",
  },
  "contact.addressTitle": {
    cs: "Residence Santa Pola",
    en: "Residence Santa Pola",
    es: "Residence Santa Pola",
    de: "Residence Santa Pola",
    fr: "Residence Santa Pola",
  },

  "legal.metaTitle": {
    cs: "Obchodní podmínky",
    en: "Terms and conditions",
    es: "Condiciones generales",
    de: "Allgemeine Geschäftsbedingungen",
    fr: "Conditions générales",
  },
  "legal.title": {
    cs: "Všeobecné obchodní podmínky",
    en: "Terms and conditions",
    es: "Condiciones generales",
    de: "Allgemeine Geschäftsbedingungen",
    fr: "Conditions générales",
  },
  "legal.body": {
    cs: "1. Tyto podmínky se vztahují na pronájem apartmánu na adrese Calle Venezuela 11, Santa Pola, Španělsko, mezi pronajímatelem a nájemcem.\n\n2. Apartmán slouží výhradně ke krátkodobému ubytování.\n\n3. Rezervace je potvrzena zaplacením zálohy 50 %. Zbytek je splatný 30 dní před příjezdem.\n\n4. Cena zahrnuje daně, energie, vodu, internet. Může být požadována kauce 200 EUR, vrácená po pobytu bez škod.\n\n5. Nájemce dodržuje místní předpisy, neubytovává další osoby bez souhlasu a zachází s bytem s péčí.\n\n6. Check-out je do 11:00, není-li dohodnuto jinak.\n\n7. Storno ze strany nájemce se řídí ceníkem na webu. Při stornu ze strany pronajímatele se vrací všechny zaplacené částky.\n\n8. Nájemce uzavře cestovní pojištění. Pronajímatel nenese odpovědnost za ztráty způsobené výpadkem sítí mimo jeho vliv.\n\n9. Sporům je příslušný soud v Alicante, právo Španělska.",
    en: "1. These terms apply to the rental of the apartment at Calle Venezuela 11, Santa Pola, Spain, between the landlord and the guest.\n\n2. The apartment is for short-term stays only.\n\n3. A booking is confirmed by paying a 50% deposit. The remainder is due 30 days before arrival.\n\n4. The price includes taxes, utilities and internet. A 200 EUR deposit may be requested and is returned after a stay without damage.\n\n5. The guest follows local rules, does not host extra people without consent, and treats the home with care.\n\n6. Check-out is by 11:00 unless agreed otherwise.\n\n7. Guest cancellations follow the rates page. If the landlord cancels, all payments are refunded.\n\n8. The guest takes out travel insurance. The landlord is not liable for utility outages beyond their control.\n\n9. Disputes fall under the courts of Alicante and Spanish law.",
    es: "1. Estas condiciones se aplican al alquiler del apartamento en Calle Venezuela 11, Santa Pola, España.\n\n2. El apartamento es solo para estancias de corta duración.\n\n3. La reserva se confirma con una señal del 50 %. El resto se paga 30 días antes de la llegada.\n\n4. El precio incluye impuestos, suministros e internet. Puede pedirse un depósito de 200 EUR, devuelto si no hay daños.\n\n5. El huésped cumple las normas locales, no aloja a más personas sin consentimiento y cuida el piso.\n\n6. La salida es antes de las 11:00 salvo pacto.\n\n7. Las cancelaciones del huésped siguen la página de tarifas. Si cancela el anfitrión, se devuelve todo.\n\n8. El huésped contrata seguro de viaje. El anfitrión no responde de cortes ajenos a su control.\n\n9. Los litigios corresponden a los tribunales de Alicante y la ley española.",
    de: "1. Diese Bedingungen gelten für die Vermietung des Apartments in der Calle Venezuela 11, Santa Pola, Spanien.\n\n2. Das Apartment dient nur dem Kurzaufenthalt.\n\n3. Die Buchung gilt mit 50 % Anzahlung als bestätigt. Der Rest ist 30 Tage vor Anreise fällig.\n\n4. Der Preis enthält Steuern, Nebenkosten und Internet. Eine Kaution von 200 EUR kann verlangt und nach schadensfreiem Aufenthalt zurückgezahlt werden.\n\n5. Der Gast hält lokale Regeln ein, beherbergt keine weiteren Personen ohne Zustimmung und geht pfleglich mit der Wohnung um.\n\n6. Check-out bis 11:00 Uhr, sofern nicht anders vereinbart.\n\n7. Stornierungen durch den Gast folgen der Preisseite. Storniert der Vermieter, werden alle Zahlungen erstattet.\n\n8. Der Gast schließt eine Reiseversicherung ab. Der Vermieter haftet nicht für Ausfälle außerhalb seines Einflusses.\n\n9. Zuständig sind die Gerichte in Alicante und spanisches Recht.",
    fr: "1. Ces conditions s’appliquent à la location de l’appartement au Calle Venezuela 11, Santa Pola, Espagne.\n\n2. L’appartement est destiné uniquement aux séjours de courte durée.\n\n3. La réservation est confirmée par un acompte de 50 %. Le solde est dû 30 jours avant l’arrivée.\n\n4. Le tarif inclut taxes, fluides et internet. Une caution de 200 EUR peut être demandée et rendue après un séjour sans dégâts.\n\n5. Le locataire respecte les règles locales, n’héberge pas d’autres personnes sans accord et prend soin du logement.\n\n6. Le départ a lieu avant 11 h sauf accord contraire.\n\n7. Les annulations du locataire suivent la page tarifs. En cas d’annulation par le propriétaire, toutes les sommes sont remboursées.\n\n8. Le locataire souscrit une assurance voyage. Le propriétaire n’est pas responsable des coupures hors de son contrôle.\n\n9. Les litiges relèvent des tribunaux d’Alicante et du droit espagnol.",
  },

  "welcome.metaTitle": {
    cs: "Vítejte · Prázdniny ve Španělsku",
    en: "Welcome · Holidays in Spain",
    es: "Bienvenida · Vacaciones en España",
    de: "Willkommen · Ferien in Spanien",
    fr: "Bienvenue · Vacances en Espagne",
  },
  "welcome.title": { cs: "Vítejte", en: "Welcome", es: "Bienvenida", de: "Willkommen", fr: "Bienvenue" },
  "welcome.lead": {
    cs: "Manuály k příjezdu a průvodce okolím ke stažení. Stránka je určená hostům s potvrzeným pobytem.",
    en: "Check-in manuals and a local guide to download. This page is for guests with a confirmed stay.",
    es: "Manuales de llegada y guía del entorno para descargar. Esta página es para huéspedes con estancia confirmada.",
    de: "Check-in-Hefte und ein Ortsführer zum Download. Diese Seite ist für Gäste mit bestätigtem Aufenthalt.",
    fr: "Manuels d’arrivée et guide des environs à télécharger. Cette page est destinée aux hôtes dont le séjour est confirmé.",
  },
  "welcome.checkin": {
    cs: "Check-in manuál",
    en: "Check-in manual",
    es: "Manual de check-in",
    de: "Check-in-Handbuch",
    fr: "Manuel d’arrivée",
  },
  "welcome.guide": {
    cs: "Průvodce Santa Pola a okolím",
    en: "Santa Pola & surroundings guide",
    es: "Guía de Santa Pola y alrededores",
    de: "Führer Santa Pola und Umgebung",
    fr: "Guide de Santa Pola et des environs",
  },
};
